export interface Student {
    id: number,
    name: string,
    firstSurname: string,
    secondSurname: string,
    personalEmailAddress: string,
    activaEmailAddress: string,
    phoneNumber: string,  
    avatar: any,
    cv: any,
    descrtiption: string,
    zipCode: string,
    id_user: number,
    prom: string,
    activa_points_balance: number,
}